name: Publish to npm (Semantic Release)

on:
  push:
    branches:
      - main # Trigger a push to the main branch

permissions:
  contents: write # To allow semantic-release to update package.json, create tags, and create releases
  issues: write # To allow semantic-release to comment release notes on related issues/PRs
  pull-requests: write # To allow semantic-release to comment release notes into the associated PR

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.SEMANTIC_RELEASE_GIT_PERMISSION_BOT_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_GIT_PERMISSION_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # To allow semantic-release to parse the entire commit history
          persist-credentials: false

      - name: Set up Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        id: setup_node_id
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run test

      - name: Build
        run: npm run type-check

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Used for npm publish
