name: Publish to npm (Semantic Release)

on:
  push:
    branches:
      - main # Trigger a push to the main branch

permissions:
  id-token: write # Required for OIDC
  contents: write # To allow semantic-release to update package.json, create tags, and create releases
  issues: write # To allow semantic-release to comment release notes on related issues/PRs
  pull-requests: write # To allow semantic-release to comment release notes into the associated PR

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ vars.SEMANTIC_RELEASE_GIT_PERMISSION_BOT_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_GIT_PERMISSION_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # To allow semantic-release to parse the entire commit history
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        id: setup_node_id
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run semantic-release
        run: pnpm exec semantic-release --dry-run # Remove `--dry-run` for actual release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Used for npm publish
