name: Style Check

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
    paths-ignore:
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: true
      matrix:
        command:
          - fmt
          - cspell
          - doc
          - check:ext
          - md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10

      - name: Set up Node.js 25.0.0
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        id: setup_node_id
        with:
          node-version: 25.0.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run "${{ matrix.command }}"
        run: pnpm run ${{ matrix.command }}

      - name: Check if there is no file diff
        run: pnpm exec assert-repo-is-clean
